// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";
import {ReentrancyGuard} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {Strings} from "@openzeppelin/contracts/utils/Strings.sol";
import {Registry} from "./Registry.sol";
import {ATNToken} from "../tokens/ATNToken.sol";
import {AutonetLib} from "../utils/AutonetLib.sol";

/**
 * @title RPB (Recursive Principled Body)
 * @notice The single contract for an RPB jurisdiction.
 *
 * Every participant is an Agent — no human/AI distinction. Root agents
 * share a wallet with the human operating the node; child agents get
 * wallets generated by their parent (parent holds the private key).
 *
 * Accepts any ERC20 token that has a parity entry in the jurisdiction's
 * Registry (key: "jurisdiction.parity.{token_address}"). All internal
 * accounting uses normalized value units (raw amount × parity ratio).
 *
 * Manages:
 * - Agent registration (lineage, alignment, sponsorship)
 * - Wallet hierarchy (parent-child key ownership, cascading drain)
 * - Training reward distribution
 * - Inference pricing and accounting
 * - RPB share issuance (claims on inference dividends)
 * - Model versioning
 */
contract RPB is Ownable, ReentrancyGuard {

    // =========================================================================
    // Structs
    // =========================================================================

    struct AgentRecord {
        address agentAddress;
        bytes32 lineageHash;              // hash(parent_lineage + charter + pubkey)
        bytes32 alignmentHash;            // hash of alignment vector
        address parentAgent;              // parent agent address (address(0) for root agents)
        address sponsorAgent;             // sponsor address (address(0) if independent)
        uint256 registeredAt;
        bool active;
        // Economic tracking (normalized value units)
        uint256 totalInferenceServed;
        uint256 totalTrainingContributions;
        uint256 totalRewardsEarned;
    }

    struct SponsorRecord {
        address sponsorAddress;
        bytes32 charterHash;              // hash of training charter / system prompt
        uint256 budgetAllocated;          // normalized value units
        uint256 budgetSpent;
        uint256 sponsoredCount;
        bool active;
    }

    struct TrainingRecord {
        address agent;
        uint256 contribution;
        uint256 epoch;
        bool rewarded;
    }

    // =========================================================================
    // State — Agent Registry
    // =========================================================================

    mapping(address => AgentRecord) public agents;
    mapping(address => SponsorRecord) public sponsors;
    mapping(bytes32 => address) public lineageToAgent;       // lineage hash -> agent address
    mapping(address => address[]) public childAgents;        // parent -> children
    mapping(address => address[]) public sponsoredAgents;    // sponsor -> sponsored agents

    address[] public registeredAgentList;    // enumerable list of all agent addresses
    uint256 public totalRegistered;
    uint256 public totalSponsors;

    // =========================================================================
    // State — Economics (all amounts in normalized value units)
    // =========================================================================

    Registry public registry;         // Jurisdiction registry (source of truth)
    address public dao;               // Governor contract (read from registry owner)

    // --- Training rewards ---
    uint256 public trainingRewardPool;
    uint256 public totalTrainingTokens;
    uint256 public currentEpoch;
    mapping(uint256 => TrainingRecord[]) public epochRecords;
    mapping(address => uint256) public agentTrainingTokens;
    mapping(address => uint256) public claimedRewards;

    // --- Per-token pool tracking (token address -> amount held in raw token units) ---
    mapping(address => uint256) public tokenPoolBalances;

    // --- RPB shares (claims on inference dividends) ---
    uint256 public totalShares;
    mapping(address => uint256) public shares;
    uint256 public totalInferenceRevenue;
    uint256 public totalDividendsPaid;
    mapping(address => uint256) public lastDividendClaim;

    // --- Inference accounting ---
    uint256 public totalInferenceUnits;
    uint256 public inferenceProviderShare;     // Basis points
    uint256 public shareholderShare;           // Basis points
    uint256 public treasuryShare;              // Basis points

    // --- Model reference ---
    bytes32 public modelArchitectureHash;
    bytes32 public currentModelHash;
    uint256 public modelVersion;

    // --- Task reward budget (replaces Project.sol budget) ---
    ATNToken public atnToken;
    uint256 public taskRewardBudgetATN;
    mapping(address => bool) public authorizedDisbursers;

    // --- Inference pricing ---
    string public modelWeightsCid;
    uint256 public atnPricePerInference;
    AutonetLib.DiscountTier[] public discountTiers;

    // =========================================================================
    // Events
    // =========================================================================

    // Agent lifecycle
    event AgentRegistered(
        address indexed agent,
        bytes32 lineageHash,
        address indexed parentAgent,
        address indexed sponsor,
        uint256 timestamp
    );
    event AgentDeactivated(address indexed agent);
    event AlignmentUpdated(address indexed agent, bytes32 newAlignmentHash);
    event SponsorRegistered(address indexed sponsor, bytes32 charterHash, uint256 budget);
    event AgentSponsored(address indexed sponsor, address indexed agent);
    event SponsorBudgetUpdated(address indexed sponsor, uint256 newBudget);
    event FundsDrained(address indexed from, address indexed to, address indexed token, uint256 amount);

    // Economics
    event TrainingRecorded(address indexed agent, uint256 contribution, uint256 epoch);
    event TrainingRewarded(address indexed agent, uint256 trainingTokens, uint256 epoch);
    event RewardClaimed(address indexed agent, address indexed token, uint256 amount);
    event SharesPurchased(address indexed buyer, uint256 shares, address indexed token, uint256 cost);
    event DividendClaimed(address indexed holder, address indexed token, uint256 amount);
    event InferenceServed(address indexed provider, address indexed requester, uint256 units, uint256 normalizedCost);
    event EpochAdvanced(uint256 newEpoch);
    event ModelUpdated(bytes32 newModelHash, uint256 version);
    event RewardPoolFunded(address indexed funder, address indexed token, uint256 amount, uint256 normalizedValue);
    event DisburserAuthorized(address indexed disburser, bool authorized);
    event TaskBudgetFunded(uint256 amount, uint256 newTotal);
    event TaskBudgetDisbursed(address indexed recipient, uint256 amount);
    event MatureModelSet(string weightsCid, uint256 price);
    event InferencePriceSet(uint256 price);
    event DiscountTiersUpdated(uint256 tierCount);

    // =========================================================================
    // Errors
    // =========================================================================

    // Agent registry
    error AlreadyRegistered();
    error LineageHashRequired();
    error LineageHashAlreadyUsed();
    error SponsorNotActive();
    error AgentNotActive();
    error MustBeRegisteredAgent();
    error AlreadySponsor();
    error NotSponsor();
    error NotParentOrSelf();

    // Economics
    error RewardPoolEmpty();
    error NoRewardsToClaim();
    error AmountMustBePositive();
    error NoShares();
    error NoSharesOutstanding();
    error NoDividendsToClaim();
    error OnlyDAO();
    error RevenueSplitInvalid();
    error TransferFailed();
    error ProviderPaymentFailed();
    error TreasuryPaymentFailed();
    error TokenNotInValueIndex();
    error InsufficientPoolBalance();
    error NotAuthorizedDisburser();
    error InsufficientBudget();
    error NotOwnerOrDAO();

    // =========================================================================
    // Constructor
    // =========================================================================

    error InvalidJurisdiction();

    constructor(
        address _registry,
        address _atnToken
    ) Ownable(msg.sender) {
        Registry reg = Registry(payable(_registry));
        if (reg.jurisdictionAddress() == address(0)) revert InvalidJurisdiction();

        registry = reg;
        dao = reg.owner();
        atnToken = ATNToken(_atnToken);

        // Default revenue split (basis points, must sum to 10000)
        inferenceProviderShare = 6000;  // 60%
        shareholderShare = 2500;        // 25%
        treasuryShare = 1500;           // 15%

        currentEpoch = 1;
    }

    // =========================================================================
    // Value Index — Parity Validation
    // =========================================================================

    /**
     * @notice Get the parity ratio for a token from the jurisdiction registry.
     * @dev Reads "jurisdiction.parity.{token_address}" — returns 0 if not found.
     */
    function _getParityValue(address token) internal view returns (uint256) {
        string memory parityKey = string.concat(
            "jurisdiction.parity.",
            Strings.toHexString(uint160(token))
        );
        string memory parityStr = registry.getRegistryValue(parityKey);
        if (bytes(parityStr).length == 0) return 0;
        return Strings.parseUint(parityStr);
    }

    /**
     * @notice Normalize a raw token amount to value units using parity.
     * @dev Reverts if the token has no parity entry in the Registry.
     */
    function _normalize(address token, uint256 rawAmount) internal view returns (uint256) {
        uint256 parity = _getParityValue(token);
        if (parity == 0) revert TokenNotInValueIndex();
        return rawAmount * parity;
    }

    /**
     * @notice Convert normalized value units back to raw token amount.
     */
    function _denormalize(address token, uint256 normalizedAmount) internal view returns (uint256) {
        uint256 parity = _getParityValue(token);
        if (parity == 0) revert TokenNotInValueIndex();
        return normalizedAmount / parity;
    }

    // =========================================================================
    // Agent Registration
    // =========================================================================

    function registerAgent(
        bytes32 lineageHash,
        bytes32 alignmentHash,
        address parentAgent,
        address sponsorAgent
    ) external nonReentrant {
        if (agents[msg.sender].registeredAt != 0) revert AlreadyRegistered();
        if (lineageHash == bytes32(0)) revert LineageHashRequired();
        if (lineageToAgent[lineageHash] != address(0)) revert LineageHashAlreadyUsed();

        if (parentAgent != address(0)) {
            if (!agents[parentAgent].active) revert AgentNotActive();
        }

        if (sponsorAgent != address(0)) {
            if (!sponsors[sponsorAgent].active) revert SponsorNotActive();
        }

        agents[msg.sender] = AgentRecord({
            agentAddress: msg.sender,
            lineageHash: lineageHash,
            alignmentHash: alignmentHash,
            parentAgent: parentAgent,
            sponsorAgent: sponsorAgent,
            registeredAt: block.timestamp,
            active: true,
            totalInferenceServed: 0,
            totalTrainingContributions: 0,
            totalRewardsEarned: 0
        });

        lineageToAgent[lineageHash] = msg.sender;
        registeredAgentList.push(msg.sender);
        totalRegistered++;

        if (parentAgent != address(0)) {
            childAgents[parentAgent].push(msg.sender);
        }

        if (sponsorAgent != address(0)) {
            sponsoredAgents[sponsorAgent].push(msg.sender);
            sponsors[sponsorAgent].sponsoredCount++;
            emit AgentSponsored(sponsorAgent, msg.sender);
        }

        emit AgentRegistered(msg.sender, lineageHash, parentAgent, sponsorAgent, block.timestamp);
    }

    function updateAlignment(bytes32 newAlignmentHash) external {
        if (!agents[msg.sender].active) revert AgentNotActive();
        agents[msg.sender].alignmentHash = newAlignmentHash;
        emit AlignmentUpdated(msg.sender, newAlignmentHash);
    }

    function deactivateAgent(address agent) external {
        if (!agents[agent].active) revert AgentNotActive();
        if (msg.sender != agent && msg.sender != agents[agent].parentAgent) {
            revert NotParentOrSelf();
        }
        agents[agent].active = false;
        emit AgentDeactivated(agent);
    }

    // =========================================================================
    // Wallet Hierarchy — Drain
    // =========================================================================

    /**
     * @notice Drain a specific token from a child agent to its parent.
     * @param child Address of the child agent to drain
     * @param token ERC20 token to drain (must be in value index)
     */
    function drainChild(address child, address token) external nonReentrant {
        AgentRecord storage childRecord = agents[child];
        if (!childRecord.active && childRecord.registeredAt == 0) revert AgentNotActive();
        if (msg.sender != childRecord.parentAgent) revert NotParentOrSelf();
        if (_getParityValue(token) == 0) revert TokenNotInValueIndex();

        uint256 balance = IERC20(token).balanceOf(child);
        if (balance > 0) {
            if (!IERC20(token).transferFrom(child, msg.sender, balance)) revert TransferFailed();
            emit FundsDrained(child, msg.sender, token, balance);
        }
    }

    /**
     * @notice Cascading drain of a specific token from all descendants.
     * @param agent Starting agent (drains all children of this agent)
     * @param token ERC20 token to drain
     */
    function drainDescendants(address agent, address token) external nonReentrant {
        if (msg.sender != agent && msg.sender != agents[agent].parentAgent) {
            revert NotParentOrSelf();
        }
        if (_getParityValue(token) == 0) revert TokenNotInValueIndex();

        address[] memory children = childAgents[agent];
        for (uint256 i = 0; i < children.length; i++) {
            _drainRecursive(children[i], agent, token);
        }
    }

    function _drainRecursive(address child, address drainTo, address token) internal {
        address[] memory grandchildren = childAgents[child];
        for (uint256 i = 0; i < grandchildren.length; i++) {
            _drainRecursive(grandchildren[i], child, token);
        }

        uint256 balance = IERC20(token).balanceOf(child);
        if (balance > 0) {
            if (IERC20(token).transferFrom(child, drainTo, balance)) {
                emit FundsDrained(child, drainTo, token, balance);
            }
        }
    }

    // =========================================================================
    // Sponsor Management
    // =========================================================================

    function registerAsSponsor(
        bytes32 charterHash,
        uint256 initialBudget
    ) external nonReentrant {
        if (!agents[msg.sender].active) revert MustBeRegisteredAgent();
        if (sponsors[msg.sender].active) revert AlreadySponsor();

        sponsors[msg.sender] = SponsorRecord({
            sponsorAddress: msg.sender,
            charterHash: charterHash,
            budgetAllocated: initialBudget,
            budgetSpent: 0,
            sponsoredCount: 0,
            active: true
        });

        totalSponsors++;
        emit SponsorRegistered(msg.sender, charterHash, initialBudget);
    }

    function updateSponsorBudget(uint256 newBudget) external {
        if (!sponsors[msg.sender].active) revert NotSponsor();
        sponsors[msg.sender].budgetAllocated = newBudget;
        emit SponsorBudgetUpdated(msg.sender, newBudget);
    }

    // =========================================================================
    // Training
    // =========================================================================

    /**
     * @notice Record a training contribution from an agent.
     * @dev Called by the owner after Proof of Intelligence verification.
     */
    function recordTraining(address agent, uint256 contribution) external onlyOwner {
        if (!agents[agent].active) revert AgentNotActive();

        epochRecords[currentEpoch].push(TrainingRecord({
            agent: agent,
            contribution: contribution,
            epoch: currentEpoch,
            rewarded: false
        }));

        agentTrainingTokens[agent] += contribution;
        totalTrainingTokens += contribution;
        agents[agent].totalTrainingContributions += contribution;

        emit TrainingRecorded(agent, contribution, currentEpoch);
        emit TrainingRewarded(agent, contribution, currentEpoch);
    }

    /**
     * @notice Claim training rewards, withdrawn in a specific value-index token.
     * @param token ERC20 token to receive (must be in value index)
     */
    function claimTrainingReward(address token) external nonReentrant {
        uint256 tokens = agentTrainingTokens[msg.sender];
        uint256 alreadyClaimed = claimedRewards[msg.sender];
        if (tokens <= alreadyClaimed) revert NoRewardsToClaim();
        if (trainingRewardPool == 0 || totalTrainingTokens == 0) revert RewardPoolEmpty();

        uint256 unclaimed = tokens - alreadyClaimed;
        uint256 normalizedReward = (unclaimed * trainingRewardPool) / totalTrainingTokens;

        if (normalizedReward > trainingRewardPool) {
            normalizedReward = trainingRewardPool;
        }

        // Convert normalized value to raw token amount
        uint256 rawAmount = _denormalize(token, normalizedReward);
        if (rawAmount == 0) revert NoRewardsToClaim();
        if (tokenPoolBalances[token] < rawAmount) revert InsufficientPoolBalance();

        claimedRewards[msg.sender] = tokens;
        trainingRewardPool -= normalizedReward;
        tokenPoolBalances[token] -= rawAmount;

        if (!IERC20(token).transfer(msg.sender, rawAmount)) revert TransferFailed();
        emit RewardClaimed(msg.sender, token, rawAmount);
    }

    /**
     * @notice Fund the training reward pool with any value-index token.
     * @param token ERC20 token to deposit (must be in value index)
     * @param amount Raw token amount to deposit
     */
    function fundTrainingPool(address token, uint256 amount) external nonReentrant {
        uint256 normalizedValue = _normalize(token, amount);
        if (!IERC20(token).transferFrom(msg.sender, address(this), amount)) revert TransferFailed();
        trainingRewardPool += normalizedValue;
        tokenPoolBalances[token] += amount;
        emit RewardPoolFunded(msg.sender, token, amount, normalizedValue);
    }

    // =========================================================================
    // RPB Shares
    // =========================================================================

    /**
     * @notice Purchase RPB shares (claims on inference dividends).
     * @param token ERC20 token to pay with (must be in value index)
     * @param amount Raw token amount to spend
     */
    function purchaseShares(address token, uint256 amount) external nonReentrant {
        if (amount == 0) revert AmountMustBePositive();
        uint256 normalizedValue = _normalize(token, amount);

        if (!IERC20(token).transferFrom(msg.sender, address(this), amount)) revert TransferFailed();

        shares[msg.sender] += normalizedValue;
        totalShares += normalizedValue;
        trainingRewardPool += normalizedValue;
        tokenPoolBalances[token] += amount;

        emit SharesPurchased(msg.sender, normalizedValue, token, amount);
    }

    /**
     * @notice Claim accumulated dividends from inference revenue.
     * @param token ERC20 token to receive dividends in (must be in value index)
     */
    function claimDividends(address token) external nonReentrant {
        if (shares[msg.sender] == 0) revert NoShares();
        if (totalShares == 0) revert NoSharesOutstanding();

        uint256 totalDividendable = (totalInferenceRevenue * shareholderShare) / 10000;
        uint256 myShare = (shares[msg.sender] * totalDividendable) / totalShares;
        uint256 alreadyClaimed = lastDividendClaim[msg.sender];

        if (myShare <= alreadyClaimed) revert NoDividendsToClaim();
        uint256 normalizedToClaim = myShare - alreadyClaimed;

        uint256 rawAmount = _denormalize(token, normalizedToClaim);
        if (rawAmount == 0) revert NoDividendsToClaim();
        if (tokenPoolBalances[token] < rawAmount) revert InsufficientPoolBalance();

        lastDividendClaim[msg.sender] = myShare;
        totalDividendsPaid += normalizedToClaim;
        tokenPoolBalances[token] -= rawAmount;

        if (!IERC20(token).transfer(msg.sender, rawAmount)) revert TransferFailed();
        emit DividendClaimed(msg.sender, token, rawAmount);
    }

    // =========================================================================
    // Inference
    // =========================================================================

    /**
     * @notice Record an inference event and distribute payment.
     * @param requester Agent that requested inference
     * @param provider Agent that served inference
     * @param units Number of inference units served
     * @param token ERC20 token used for payment (must be in value index)
     * @param cost Raw token amount for the inference cost
     */
    function recordInference(
        address requester,
        address provider,
        uint256 units,
        address token,
        uint256 cost
    ) external onlyOwner nonReentrant {
        if (!agents[provider].active) revert AgentNotActive();

        uint256 normalizedCost = _normalize(token, cost);

        totalInferenceUnits += units;
        totalInferenceRevenue += normalizedCost;
        agents[provider].totalInferenceServed += units;

        // Debit sponsor budget if provider is sponsored
        if (agents[provider].sponsorAgent != address(0)) {
            address sponsor = agents[provider].sponsorAgent;
            if (sponsors[sponsor].active) {
                sponsors[sponsor].budgetSpent += normalizedCost;
            }
        }

        // Split revenue (in raw token amounts)
        uint256 providerPayment = (cost * inferenceProviderShare) / 10000;
        uint256 treasuryPayment = (cost * treasuryShare) / 10000;
        uint256 shareholderPoolPayment = cost - providerPayment - treasuryPayment;

        if (providerPayment > 0) {
            if (!IERC20(token).transfer(provider, providerPayment)) revert ProviderPaymentFailed();
        }

        if (treasuryPayment > 0) {
            if (!IERC20(token).transfer(dao, treasuryPayment)) revert TreasuryPaymentFailed();
        }

        // Shareholder portion stays in the contract for dividend claims
        if (shareholderPoolPayment > 0) {
            tokenPoolBalances[token] += shareholderPoolPayment;
        }

        emit InferenceServed(provider, requester, units, normalizedCost);
    }

    /**
     * @notice Record an inference completed via BME (burn-mint) bridge.
     *
     *         The bridge handles all token minting. This function only updates
     *         RPB accounting so that shareholder dividends and agent stats
     *         reflect inference activity.
     *
     *         The bridge MUST mint `shareholderAmount` of ATN to this contract
     *         before calling, so that dividend claims can be honored.
     *
     * @param requester       Address that requested inference
     * @param provider        Address that served inference
     * @param units           Number of inference units served
     * @param totalRevenue    Total ATN value of the inference (burned amount)
     * @param shareholderAmount ATN minted to this contract for shareholder dividends
     */
    function recordInferenceBME(
        address requester,
        address provider,
        uint256 units,
        uint256 totalRevenue,
        uint256 shareholderAmount
    ) external nonReentrant {
        if (!authorizedDisbursers[msg.sender] && msg.sender != dao && msg.sender != owner()) {
            revert NotAuthorizedDisburser();
        }

        totalInferenceUnits += units;
        totalInferenceRevenue += totalRevenue;

        // Update agent stats if provider is a registered agent
        if (agents[provider].active) {
            agents[provider].totalInferenceServed += units;

            if (agents[provider].sponsorAgent != address(0)) {
                address sponsor = agents[provider].sponsorAgent;
                if (sponsors[sponsor].active) {
                    sponsors[sponsor].budgetSpent += totalRevenue;
                }
            }
        }

        // Track shareholder pool (bridge already minted ATN to this contract)
        if (shareholderAmount > 0) {
            tokenPoolBalances[address(atnToken)] += shareholderAmount;
        }

        emit InferenceServed(provider, requester, units, totalRevenue);
    }

    // =========================================================================
    // Model Management
    // =========================================================================

    function updateModel(bytes32 newModelHash) external onlyOwner {
        currentModelHash = newModelHash;
        modelVersion++;
        emit ModelUpdated(newModelHash, modelVersion);
    }

    function setModelArchitecture(bytes32 archHash) external onlyOwner {
        modelArchitectureHash = archHash;
    }

    // =========================================================================
    // Task Budget & Disbursement (replaces Project.sol)
    // =========================================================================

    function setAuthorizedDisburser(address _disburser, bool _authorized) external {
        if (msg.sender != owner() && msg.sender != dao) revert NotOwnerOrDAO();
        authorizedDisbursers[_disburser] = _authorized;
        emit DisburserAuthorized(_disburser, _authorized);
    }

    function fundTaskBudget(uint256 _amount) external nonReentrant {
        require(IERC20(address(atnToken)).transferFrom(msg.sender, address(this), _amount), "Transfer failed");
        taskRewardBudgetATN += _amount;
        emit TaskBudgetFunded(_amount, taskRewardBudgetATN);
    }

    function disburseFromBudget(address _recipient, uint256 _amount) external returns (bool) {
        if (!authorizedDisbursers[msg.sender] && msg.sender != dao && msg.sender != owner()) {
            revert NotAuthorizedDisburser();
        }
        if (taskRewardBudgetATN < _amount) revert InsufficientBudget();

        taskRewardBudgetATN -= _amount;
        require(IERC20(address(atnToken)).transfer(_recipient, _amount), "Transfer failed");
        emit TaskBudgetDisbursed(_recipient, _amount);
        return true;
    }

    // =========================================================================
    // Mature Model & Inference Pricing (replaces Project.sol)
    // =========================================================================

    function setMatureModel(string memory _weightsCid, uint256 _price) external {
        if (msg.sender != owner() && msg.sender != dao) revert NotOwnerOrDAO();
        modelWeightsCid = _weightsCid;
        atnPricePerInference = _price;
        emit MatureModelSet(_weightsCid, _price);
        emit InferencePriceSet(_price);
    }

    function getMatureModel() external view returns (string memory weightsCid, uint256 price) {
        return (modelWeightsCid, atnPricePerInference);
    }

    function setDiscountTiers(AutonetLib.DiscountTier[] memory _tiers) external {
        if (msg.sender != owner() && msg.sender != dao) revert NotOwnerOrDAO();
        delete discountTiers;
        for (uint i = 0; i < _tiers.length; i++) {
            discountTiers.push(_tiers[i]);
        }
        emit DiscountTiersUpdated(_tiers.length);
    }

    function getEffectivePrice(address _user) public view returns (uint256) {
        uint256 userShares = shares[_user];
        uint256 discount = 0;

        for (uint i = 0; i < discountTiers.length; i++) {
            if (userShares >= discountTiers[i].ptThreshold && discountTiers[i].discountPermille > discount) {
                discount = discountTiers[i].discountPermille;
            }
        }

        require(discount <= 1000, "Invalid discount");
        return (atnPricePerInference * (1000 - discount)) / 1000;
    }

    function getDiscountTierCount() external view returns (uint256) {
        return discountTiers.length;
    }

    // =========================================================================
    // Epoch Management
    // =========================================================================

    function advanceEpoch() external onlyOwner {
        currentEpoch++;
        emit EpochAdvanced(currentEpoch);
    }

    // =========================================================================
    // Governance
    // =========================================================================

    function updateRevenueSplit(
        uint256 _providerShare,
        uint256 _shareholderShare,
        uint256 _treasuryShare
    ) external {
        if (msg.sender != dao) revert OnlyDAO();
        if (_providerShare + _shareholderShare + _treasuryShare != 10000) revert RevenueSplitInvalid();
        inferenceProviderShare = _providerShare;
        shareholderShare = _shareholderShare;
        treasuryShare = _treasuryShare;
    }

    // =========================================================================
    // View Functions
    // =========================================================================

    function isRegistered(address agent) external view returns (bool) {
        return agents[agent].registeredAt > 0;
    }

    function isActive(address agent) external view returns (bool) {
        return agents[agent].active;
    }

    function isSponsor(address agent) external view returns (bool) {
        return sponsors[agent].active;
    }

    function getChildren(address agent) external view returns (address[] memory) {
        return childAgents[agent];
    }

    function getSponsoredAgents(address sponsor) external view returns (address[] memory) {
        return sponsoredAgents[sponsor];
    }

    function getSponsorBudgetRemaining(address sponsor) external view returns (uint256) {
        SponsorRecord storage s = sponsors[sponsor];
        if (s.budgetAllocated <= s.budgetSpent) return 0;
        return s.budgetAllocated - s.budgetSpent;
    }

    function getTrainingTokens(address agent) external view returns (uint256) {
        return agentTrainingTokens[agent];
    }

    function getUnclaimedRewards(address agent) external view returns (uint256) {
        uint256 tokens = agentTrainingTokens[agent];
        uint256 claimed = claimedRewards[agent];
        if (tokens <= claimed || trainingRewardPool == 0 || totalTrainingTokens == 0) return 0;
        uint256 unclaimed = tokens - claimed;
        return (unclaimed * trainingRewardPool) / totalTrainingTokens;
    }

    function getShareBalance(address holder) external view returns (uint256) {
        return shares[holder];
    }

    function getUnclaimedDividends(address holder) external view returns (uint256) {
        if (shares[holder] == 0 || totalShares == 0) return 0;
        uint256 totalDividendable = (totalInferenceRevenue * shareholderShare) / 10000;
        uint256 myShare = (shares[holder] * totalDividendable) / totalShares;
        uint256 claimed = lastDividendClaim[holder];
        if (myShare <= claimed) return 0;
        return myShare - claimed;
    }

    function getExchangeRate() external view returns (uint256 numerator, uint256 denominator) {
        return (trainingRewardPool, totalTrainingTokens > 0 ? totalTrainingTokens : 1);
    }

    function getTokenParity(address token) external view returns (uint256) {
        return _getParityValue(token);
    }

    function getTokenPoolBalance(address token) external view returns (uint256) {
        return tokenPoolBalances[token];
    }

    function getRegisteredAgents() external view returns (address[] memory) {
        return registeredAgentList;
    }

    function getConstitution() external view returns (string memory) {
        return registry.getRegistryValue("rpb.prompt.current");
    }
}
