#!/usr/bin/env python3
"""End-to-end proof that a PURCHASED inference service actually SERVES.

The sibling script ``local_e2e_service_provider.py`` proves the economics with
the model seam MOCKED: two in-process Runtimes, a ``CannedProvider`` standing in
for the seller's stack. That leaves the one question a buyer actually cares
about unanswered — does the thing I paid for think?

This script answers it with NOTHING mocked:

  * TWO REAL DAEMON PROCESSES — ``python -m atn`` subprocesses, each with its
    own isolated home (``USERPROFILE`` redirect), its own config.yaml, its own
    WS port. No in-process shortcut: every frame crosses a real socket between
    two real OS processes.
  * A REAL MODEL — the provider daemon serves off its own provider stack
    (ollama, a locally-installed model). The completion is generated by a real
    LLM, and the assertion is that it ANSWERS a distinguishable prompt: we ask
    for a specific rare word and require it in the reply. A canned responder
    cannot pass that.
  * A REAL AGENT TURN — the consumer's child agent is driven through
    ``send_agent_message``, the production surface a human's app uses. The
    child's bound ``ServiceProvider`` resolves, pays, dials, and the completion
    comes back into the agent's execution record.

The economic loop under test is the one ratified 2026-07-26
(``docs/services_market.md``, "Decision (2026-07-26): LLM inference as a
marketplace service" + the employer-chooses-the-tool ruling):

    provider daemon registers an inference-backed service (WS + on-chain
    ServiceRegistry + on-chain wss endpoint)
      -> consumer daemon's parent agent creates a CHILD bound to that service
      -> parent funds the child's own wallet
      -> the child does an ordinary agent turn
      -> real Substrate.payForService signed with the CHILD'S key
      -> provider gate verifies the payment on chain (not degraded)
      -> the REAL MODEL serves the work item over the real wss wire
      -> a replayed request_id is refused

Stages
------
  1  chain up (hardhat node + Substrate + ServiceRegistry)
  2  model up (ollama reachable, a real model installed)
  3  provider daemon boots (real subprocess, isolated home, port 7710)
  4  consumer daemon boots (real subprocess, isolated home, port 7720)
  5  agents on chain (provider agent, consumer parent + child, funded)
  6  provider lists an inference-backed service (WS + chain + endpoint)
  7  parent binds the child, child does a REAL agent turn on purchased cognition
  8  settlement (ServicePayment event, provider request log, replay refused)
  9  teardown

Running it remotely
-------------------
Every endpoint is an env var with a fully-local default, so the same script
re-runs with the consumer on another machine:

    E2E_RPC_URL        chain RPC both daemons dial   (default http://127.0.0.1:8545)
    E2E_PROVIDER_WS    the ws:// URL published ON CHAIN for the provider —
                       what the consumer actually dials
                       (default ws://127.0.0.1:7710)
    E2E_PROVIDER_HOST  bind host for the provider daemon's listener
                       (default 127.0.0.1; use 0.0.0.0 to accept off-box)
    E2E_CONSUMER_HOST  bind host for the consumer daemon's listener
                       (default 127.0.0.1)
    E2E_PROVIDER_PORT  provider daemon WS port  (default 7710)
    E2E_CONSUMER_PORT  consumer daemon WS port  (default 7720)
    E2E_HARDHAT_HOST   hardhat node bind host   (default 0.0.0.0, reachable)
    E2E_OLLAMA_URL     provider daemon's model backend
                       (default http://127.0.0.1:11434)
    E2E_MODEL          served model id (default: first installed ollama model)
    E2E_SKIP_PROVIDER  "1" => don't launch the provider daemon; assume one is
                       already serving at E2E_PROVIDER_WS (the split-machine
                       run: launch the provider side on box A, then run this
                       with the flag on box B)
    E2E_PROVIDER_HOLD  "1" => run the PROVIDER SIDE ONLY (stages 1,2,3,5a,6),
                       print the exports the consumer box needs, and wait until
                       Ctrl+C or the sentinel file appears, tearing everything
                       down on the way out. The other half of
                       E2E_SKIP_PROVIDER.
    E2E_HOLD_SENTINEL  path whose appearance ends a hold (default: a file named
                       ``e2e_provider_release`` beside the provider's temp home)

  Consumer-side inputs (printed by the hold side; only read when
  E2E_SKIP_PROVIDER=1):

    E2E_SUBSTRATE         deployed Substrate address
    E2E_SERVICE_REGISTRY  deployed ServiceRegistry address
    E2E_SPEC_DIGEST       the service spec digest the provider listed
    E2E_PROVIDER_ADDR     the selling agent's 0x (payment recipient)
    E2E_PROVIDER_ANCHOR   "1" (default) => the consumer submits its own epoch
                          anchor to fund the child. Set 0 if the provider side
                          already anchored the epoch id in use.

Run (single box):
    python scripts/local_e2e_cross_daemon_inference.py

Run (two boxes) — on the PROVIDER box:
    E2E_PROVIDER_HOLD=1 E2E_PROVIDER_HOST=0.0.0.0 \
    E2E_PROVIDER_WS=ws://<reachable-ip>:7711 \
      python scripts/local_e2e_cross_daemon_inference.py
then paste the printed exports on the CONSUMER box and:
    E2E_SKIP_PROVIDER=1 python scripts/local_e2e_cross_daemon_inference.py

See docs/local_e2e.md and docs/services_market.md.

A NOTE ON THE PROVIDER'S OFF-BOX LISTENER
-----------------------------------------
The daemon's privileged listener is loopback-only and NOT configurable
(``atn/cli.py`` pins ``host="localhost"``) — by design: it is pre-authed as
owner and exports keys. Off-box reachability is the REMOTE listener
(``autonet.remote_ws_host`` / ``remote_ws_port``), which is auth-required.

A paying counterparty on another machine can never pass that handshake: it is
not this daemon's owner and holds no key in this daemon's fleet. So
``service_request`` is dispatched pre-auth on the remote listener
(``PAYMENT_AUTHORIZED_MESSAGES`` in ``atn/ws_server.py``) — the on-chain
payment IS the credential, which is the doctrine in docs/services_market.md §3.
When E2E_PROVIDER_HOST is not loopback, the hold side therefore publishes the
REMOTE listener's port on chain, and E2E_PROVIDER_WS must name it.
"""
from __future__ import annotations

import asyncio
import json
import os
import shutil
import subprocess
import sys
import tempfile
import time
import traceback
from pathlib import Path
from typing import Any, Dict, List, Optional

REPO = Path(__file__).resolve().parent.parent
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

# --------------------------------------------------------------------------
# Parameterization — every endpoint an env var, all defaults fully local
# --------------------------------------------------------------------------

RPC_URL = os.environ.get("E2E_RPC_URL", "http://127.0.0.1:8545")
# `npx hardhat node` serves the in-process "hardhat" network (chainId 1337,
# see hardhat.config.js) — NOT 31337. Signing for the wrong id gives
# "incompatible EIP-155 transaction, signed for another chain".
CHAIN_ID = 1337
# Bind hardhat wide by default: cheap, and it is what lets a consumer on
# another machine dial the same chain.
HARDHAT_HOST = os.environ.get("E2E_HARDHAT_HOST", "0.0.0.0")

PROVIDER_PORT = int(os.environ.get("E2E_PROVIDER_PORT", "7710"))
CONSUMER_PORT = int(os.environ.get("E2E_CONSUMER_PORT", "7720"))
PROVIDER_HOST = os.environ.get("E2E_PROVIDER_HOST", "127.0.0.1")
CONSUMER_HOST = os.environ.get("E2E_CONSUMER_HOST", "127.0.0.1")
# Off-box reachability is the daemon's REMOTE (auth-required) listener; the
# privileged one is pinned to loopback in atn/cli.py. Only enabled when
# E2E_PROVIDER_HOST is not loopback — a single-box run needs nothing extra.
PROVIDER_REMOTE_PORT = int(
    os.environ.get("E2E_PROVIDER_REMOTE_PORT", str(PROVIDER_PORT + 1)))
PROVIDER_OFFBOX = PROVIDER_HOST not in ("127.0.0.1", "localhost", "::1", "")
# The port that actually accepts an off-box buyer.
PROVIDER_WIRE_PORT = PROVIDER_REMOTE_PORT if PROVIDER_OFFBOX else PROVIDER_PORT
# The endpoint published ON CHAIN — the address the consumer resolves and
# dials. Distinct from the bind host: behind NAT/ZeroTier the reachable
# address is not the bind address.
PROVIDER_WS = os.environ.get(
    "E2E_PROVIDER_WS", f"ws://{PROVIDER_HOST}:{PROVIDER_WIRE_PORT}")
OLLAMA_URL = os.environ.get("E2E_OLLAMA_URL", "http://127.0.0.1:11434")
MODEL = os.environ.get("E2E_MODEL", "")
SKIP_PROVIDER = os.environ.get("E2E_SKIP_PROVIDER", "") == "1"
PROVIDER_HOLD = os.environ.get("E2E_PROVIDER_HOLD", "") == "1"

# Consumer-side inputs for a split run (printed by the hold side).
EXT_SUBSTRATE = os.environ.get("E2E_SUBSTRATE", "").strip()
EXT_REGISTRY = os.environ.get("E2E_SERVICE_REGISTRY", "").strip()
EXT_SPEC_DIGEST = os.environ.get("E2E_SPEC_DIGEST", "").strip()
EXT_PROVIDER_ADDR = os.environ.get("E2E_PROVIDER_ADDR", "").strip()
CONSUMER_ANCHORS = os.environ.get("E2E_PROVIDER_ANCHOR", "1") != "0"
HOLD_SENTINEL = os.environ.get("E2E_HOLD_SENTINEL", "").strip()

# Hardhat's deterministic mnemonic accounts (well-known, safe: local only).
# account[0] = the PROVIDER's human wallet (deployer, the seller)
# account[1] = the CONSUMER's human wallet (the employer funding the child)
HH_ACCT0_PK = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
HH_ACCT1_PK = "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"

SERVICE_ASK = 1000            # ATN base units per work item
CHILD_FUNDING = 100_000       # ATN the employer allocates to the child
MAX_TOKENS_CAP = 512          # the declared output ceiling the ask is priced at

# The distinguishability probe. A canned responder cannot produce this: the
# word is arbitrary, and the assertion is that the MODEL echoed the word we
# asked for. Kept trivially easy so a small local model reliably complies.
MAGIC_WORD = "PINEAPPLE"
PROBE_PROMPT = (
    f"Reply with exactly one word, the word {MAGIC_WORD}, and nothing else."
)

# Timeouts. A cold local model loads for ~20s and a real agent turn adds the
# framework's own overhead, so these are deliberately generous.
DAEMON_BOOT_TIMEOUT = 180.0   # daemon boot: heavy imports (numpy, world_model)
INFERENCE_TIMEOUT = 300.0     # the agent turn: pay + dial + cold model load
WS_CALL_TIMEOUT = 240.0       # a single WS round trip that may drive inference


# ---------------------------------------------------------------------------
# Scoreboard
# ---------------------------------------------------------------------------

class _SkipStage(Exception):
    """Raised inside a stage body to jump to its end without failing it.

    Used by the split-machine modes: a stage that belongs to the OTHER box has
    already set itself SKIP and has nothing left to do, but the stage bodies are
    long linear blocks and an early `return` would abandon the run. The stage's
    own ``except`` re-raises nothing for this type.
    """


class Stage:
    def __init__(self, num: int, name: str):
        self.num = num
        self.name = name
        self.status = "PENDING"  # PASS | FAIL | SKIP
        self.notes: List[str] = []

    def note(self, k: str, v: Any) -> None:
        self.notes.append(f"{k}={v}")


class Board:
    def __init__(self) -> None:
        self.stages: Dict[int, Stage] = {}

    def stage(self, num: int, name: str) -> Stage:
        s = Stage(num, name)
        self.stages[num] = s
        return s

    def render(self) -> str:
        lines = ["", "=" * 74,
                 "  CROSS-DAEMON REAL-INFERENCE E2E — SCOREBOARD", "=" * 74]
        for num in sorted(self.stages):
            s = self.stages[num]
            mark = {"PASS": "PASS", "FAIL": "FAIL", "SKIP": "SKIP",
                    "PENDING": "----"}[s.status]
            lines.append(f"  [{mark}] Stage {s.num} — {s.name}")
            for n in s.notes:
                lines.append(f"           {n}")
        lines.append("=" * 74)
        n_pass = sum(1 for s in self.stages.values() if s.status == "PASS")
        n_fail = sum(1 for s in self.stages.values() if s.status == "FAIL")
        n_skip = sum(1 for s in self.stages.values() if s.status == "SKIP")
        lines.append(f"  {n_pass} PASS / {n_fail} FAIL / {n_skip} SKIP")
        lines.append("=" * 74)
        return "\n".join(lines)


def _safe(msg: str) -> str:
    """Strip anything the console codec can't encode.

    Windows consoles default to cp1252; a daemon log tail carrying a rich-console
    box-drawing char or an em dash crashes ``print`` with a UnicodeEncodeError —
    which would then mask the real failure we were trying to report.
    """
    enc = getattr(sys.stdout, "encoding", None) or "utf-8"
    return msg.encode(enc, errors="replace").decode(enc, errors="replace")


def log(msg: str) -> None:
    print(_safe(f"[e2e] {msg}"), flush=True)


def step(msg: str) -> None:
    print(_safe(f"  PASS  {msg}"), flush=True)


# ---------------------------------------------------------------------------
# Chain harness
# ---------------------------------------------------------------------------

def _npx() -> str:
    return "npx.cmd" if os.name == "nt" else "npx"


def start_hardhat(cwd: Path) -> subprocess.Popen:
    """Launch `npx hardhat node` detached; caller polls the RPC.

    Bound to HARDHAT_HOST (0.0.0.0 by default) so a consumer daemon on another
    machine can dial the same chain — the whole point of parameterizing.

    stdout/stderr go to DEVNULL: the node logs every RPC call and a filled
    PIPE buffer blocks the process (surfaces as an undici HeadersTimeoutError
    on the deploy side).
    """
    creationflags = 0
    if os.name == "nt":
        creationflags = subprocess.CREATE_NEW_PROCESS_GROUP
    return subprocess.Popen(
        [_npx(), "hardhat", "node", "--hostname", HARDHAT_HOST],
        cwd=str(cwd),
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        shell=(os.name == "nt"),
        creationflags=creationflags,
    )


def wait_rpc(timeout: float = 60.0) -> bool:
    from web3 import Web3
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            w3 = Web3(Web3.HTTPProvider(RPC_URL))
            if w3.is_connected() and w3.eth.block_number >= 0:
                return True
        except Exception:
            pass
        time.sleep(0.5)
    return False


def kill_proc_tree(proc: Optional[subprocess.Popen], label: str = "") -> None:
    """Kill a subprocess and its children. The daemon spawns worker processes
    and hardhat spawns node, so a bare terminate() orphans them."""
    if proc is None:
        return
    if proc.poll() is not None:
        return
    try:
        if os.name == "nt":
            subprocess.run(["taskkill", "/F", "/T", "/PID", str(proc.pid)],
                           capture_output=True, shell=True)
        else:
            proc.terminate()
        proc.wait(timeout=15)
    except Exception:
        try:
            proc.kill()
            proc.wait(timeout=5)
        except Exception:
            pass
    if label:
        log(f"{label} torn down")


def load_abi(name: str) -> list:
    """Load a compiled contract ABI from Hardhat artifacts.

    ServiceMarket.sol holds several contracts, so the .sol stem differs from
    the contract name — scan the tree rather than guess.
    """
    art = REPO / "artifacts" / "contracts"
    for sub in ("core", "test"):
        for sol in (name, "ServiceMarket"):
            p = art / sub / f"{sol}.sol" / f"{name}.json"
            if p.exists():
                with p.open("r", encoding="utf-8") as fh:
                    return json.load(fh)["abi"]
    for p in art.rglob(f"{name}.json"):
        if p.parent.name.endswith(".sol"):
            with p.open("r", encoding="utf-8") as fh:
                return json.load(fh)["abi"]
    raise FileNotFoundError(f"no artifact ABI for {name} under {art}")


DEPLOY_JS = r"""
const { ethers } = require("hardhat");
const fs = require("fs");
async function main() {
  const [deployer] = await ethers.getSigners();
  const zero = "0x0000000000000000000000000000000000000000";
  // Substrate(treasury, vaultMinter, governor). governor=zero => the service
  // fee is frozen at its 2.5% default, which is what this script asserts.
  const Substrate = await ethers.getContractFactory("Substrate");
  const substrate = await Substrate.deploy(deployer.address, zero, zero);
  await substrate.waitForDeployment();
  const substrateAddr = await substrate.getAddress();

  // ServiceRegistry's constructor takes the substrate address. PaymentChannel
  // is not deployed: this rail settles by DIRECT payForService per call
  // (channels are the v2 upgrade).
  const Registry = await ethers.getContractFactory("ServiceRegistry");
  const registry = await Registry.deploy(substrateAddr);
  await registry.waitForDeployment();
  const registryAddr = await registry.getAddress();

  const out = { substrate: substrateAddr, serviceRegistry: registryAddr };
  fs.writeFileSync(process.env.DEPLOY_OUT, JSON.stringify(out, null, 2));
  console.log("DEPLOYED " + JSON.stringify(out));
}
main().catch((e) => { console.error(e); process.exit(1); });
"""


def deploy_contracts(cwd: Path) -> Dict[str, Optional[str]]:
    scripts_dir = cwd / "scripts"
    tmp_js = scripts_dir / "_e2e_xdaemon_deploy_tmp.js"
    out_json = cwd / "deployments" / "_e2e_cross_daemon.json"
    out_json.parent.mkdir(parents=True, exist_ok=True)
    tmp_js.write_text(DEPLOY_JS, encoding="utf-8")
    try:
        env = dict(os.environ)
        env["DEPLOY_OUT"] = str(out_json)
        log("deploying Substrate + ServiceRegistry via hardhat run…")
        proc = subprocess.run(
            [_npx(), "hardhat", "run", str(tmp_js), "--network", "localhost"],
            cwd=str(cwd), capture_output=True, text=True, timeout=300,
            shell=(os.name == "nt"), env=env,
        )
        if proc.returncode != 0:
            raise RuntimeError(
                f"deploy failed (rc={proc.returncode}):\n"
                f"STDOUT:\n{proc.stdout}\nSTDERR:\n{proc.stderr}")
        return json.loads(out_json.read_text(encoding="utf-8"))
    finally:
        try:
            tmp_js.unlink()
        except OSError:
            pass


def resolve_binding_shape(substrate_abi: list) -> Dict[str, Any]:
    """Discover which owner-binding surface the deployed contract exposes
    (registerAgentBound vs the older registerAgentSponsored)."""
    fns = {a["name"]: a for a in substrate_abi if a.get("type") == "function"}
    shape: Dict[str, Any] = {}
    shape["register"] = ("registerAgentBound" if "registerAgentBound" in fns
                         else "registerAgentSponsored"
                         if "registerAgentSponsored" in fns else None)
    shape["hash_view"] = ("bindingHash" if "bindingHash" in fns
                          else "sponsorshipHash" if "sponsorshipHash" in fns
                          else None)
    shape["nonce_view"] = ("bindingNonce" if "bindingNonce" in fns
                           else "sponsorshipNonce" if "sponsorshipNonce" in fns
                           else None)
    return shape


def sign_binding_digest(contract, shape: Dict[str, Any], owner_pk: str,
                        agent_addr: str, parent_addr: str, nonce: int) -> bytes:
    """Ask the CONTRACT for the exact EIP-712 digest, then sign that raw
    digest. Sidesteps any struct-field / typehash drift entirely."""
    from eth_account import Account

    view_fn = getattr(contract.functions, shape["hash_view"])
    view_abi = next(a for a in contract.abi
                    if a.get("type") == "function"
                    and a["name"] == shape["hash_view"])
    if len(view_abi["inputs"]) >= 3:
        digest = view_fn(agent_addr, parent_addr, nonce).call()
    else:
        digest = view_fn(agent_addr, parent_addr).call()
    digest = bytes(digest)
    acct = Account.from_key(owner_pk)
    signed = (Account._sign_hash(digest, acct._private_key)
              if hasattr(Account, "_sign_hash")
              else acct.unsafe_sign_hash(digest))
    return bytes(signed.signature)


def send_tx(w3, call, pk: str, addr: str, gas: int = 1_500_000) -> str:
    tx = call.build_transaction({
        "from": addr,
        "nonce": w3.eth.get_transaction_count(addr),
        "gas": gas, "gasPrice": w3.eth.gas_price, "chainId": CHAIN_ID,
    })
    signed = w3.eth.account.sign_transaction(tx, pk)
    raw = getattr(signed, "raw_transaction", None) or signed.rawTransaction
    tx_hash = w3.eth.send_raw_transaction(raw)
    receipt = w3.eth.wait_for_transaction_receipt(tx_hash, timeout=90)
    if receipt.status != 1:
        raise RuntimeError(f"tx reverted: {receipt}")
    return tx_hash.hex()


def fund_gas(w3, from_acct, to_addr: str, ether: int = 1) -> None:
    tx = {
        "from": from_acct.address, "to": to_addr,
        "value": w3.to_wei(ether, "ether"),
        "nonce": w3.eth.get_transaction_count(from_acct.address),
        "gas": 21000, "gasPrice": w3.eth.gas_price, "chainId": CHAIN_ID,
    }
    signed = w3.eth.account.sign_transaction(tx, from_acct._private_key.hex())
    raw = getattr(signed, "raw_transaction", None) or signed.rawTransaction
    w3.eth.wait_for_transaction_receipt(
        w3.eth.send_raw_transaction(raw), timeout=90)


def register_agent_on_chain(w3, substrate, shape, *, agent_pk: str,
                            agent_addr: str, owner_acct, lineage_hash: bytes,
                            peer_id: bytes) -> str:
    """Owner-bound registration signed by the agent's own key."""
    nonce_val = 0
    if shape["nonce_view"]:
        nonce_val = getattr(substrate.functions,
                            shape["nonce_view"])(agent_addr).call()
    ZERO = "0x" + "00" * 20
    sig = sign_binding_digest(substrate, shape,
                              owner_acct._private_key.hex(),
                              agent_addr, ZERO, nonce_val)
    reg_fn = getattr(substrate.functions, shape["register"])
    return send_tx(
        w3,
        reg_fn(lineage_hash, peer_id, owner_acct.address, ZERO, sig),
        agent_pk, agent_addr)


def fund_agent_atn(w3, substrate, *, epoch_id: str, agent_addr: str,
                   agent_key: str, amount: int, anchor_pk: str,
                   anchor_addr: str) -> int:
    """Mint ATN into an agent's own wallet through the PRODUCTION rail.

    Substrate has no admin mint: ATN only enters existence via the epoch close.
    So we anchor an epoch whose agentMintRoot commits this agent's share, then
    have the AGENT record its own mint from its own key. That is also the honest
    story of where an agent's operating float comes from — the network allocates
    it in the close and the agent claims it itself.
    """
    from eth_utils import keccak
    from nodes.common.mint_merkle import mint_merkle_proof, mint_merkle_root

    epoch_hash = keccak(text=epoch_id)
    # mint_scale=1: `amount` is already in base units.
    mint_map = {agent_addr: float(amount)}
    mint_root = mint_merkle_root(mint_map, 1)
    proof = mint_merkle_proof(mint_map, agent_addr, 1) or []
    ZERO32 = b"\x00" * 32
    # submitAnchor HASH-CHAINS: prevEpochRoot/prevAnchorHash must equal the
    # contract's current latest*, not zeros. Zeros are right only for the very
    # first anchor — and in a split run the provider box anchors first, so the
    # consumer's anchor would revert with PrevAnchorHashMismatch. Read the head.
    prev_epoch_root = bytes(substrate.functions.latestEpochRoot().call())
    prev_anchor_hash = bytes(substrate.functions.latestAnchorHash().call())
    send_tx(w3, substrate.functions.submitAnchor(
        epoch_id,          # epochId (string)
        ZERO32,            # epochRoot (unused by this rail)
        prev_epoch_root,   # prevEpochRoot — the chain head
        prev_anchor_hash,  # prevAnchorHash — the chain head
        "",                # agentMintCid (blob served off-chain)
        ZERO32,            # payloadHash
        mint_root,         # agentMintRoot — what the proof verifies against
    ), anchor_pk, anchor_addr)
    send_tx(w3, substrate.functions.recordTrainingForEpoch(
        amount, epoch_hash, proof), agent_key, agent_addr)
    return substrate.functions.balanceOf(agent_addr).call()


# ---------------------------------------------------------------------------
# Model backend (the REAL model — nothing canned)
# ---------------------------------------------------------------------------

def probe_ollama() -> List[str]:
    """Installed ollama model ids, or [] when the server is unreachable."""
    import httpx
    try:
        r = httpx.get(f"{OLLAMA_URL.rstrip('/')}/api/tags", timeout=10.0)
        r.raise_for_status()
        return [m.get("name", "") for m in (r.json().get("models") or [])
                if m.get("name")]
    except Exception as exc:  # noqa: BLE001
        log(f"ollama probe failed at {OLLAMA_URL}: {exc}")
        return []


def maybe_start_ollama() -> Optional[subprocess.Popen]:
    """Start `ollama serve` if the binary is around and nothing is listening.

    Returns the process we started (so we tear it down) or None when ollama was
    already up / not installed — never kill a server the user was already using.
    """
    exe = shutil.which("ollama")
    if not exe:
        return None
    log(f"starting ollama serve ({exe})…")
    proc = subprocess.Popen(
        [exe, "serve"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        creationflags=(subprocess.CREATE_NEW_PROCESS_GROUP
                       if os.name == "nt" else 0),
    )
    deadline = time.time() + 30.0
    while time.time() < deadline:
        if probe_ollama():
            return proc
        time.sleep(1.0)
    kill_proc_tree(proc)
    return None


def warm_model(model: str) -> bool:
    """Pre-load the model so the first PAID call isn't also the cold load.

    Not a shortcut: the paid call still goes through the whole rail. This only
    moves ~20s of GGUF load out of the timed cross-daemon hop, the same thing
    any real provider's daemon does by keeping a model resident.
    """
    import httpx
    try:
        r = httpx.post(
            f"{OLLAMA_URL.rstrip('/')}/api/chat",
            json={"model": model, "stream": False, "think": False,
                  "messages": [{"role": "user", "content": "hi"}],
                  "options": {"num_predict": 4}},
            timeout=240.0)
        r.raise_for_status()
        return True
    except Exception as exc:  # noqa: BLE001
        log(f"model warm-up failed: {exc}")
        return False


# ---------------------------------------------------------------------------
# Real daemon subprocesses
# ---------------------------------------------------------------------------

def write_daemon_config(home: Path, *, cfg: Dict[str, Any]) -> Path:
    """Write an isolated ~/.atn/config.yaml inside a temp home.

    The daemon has no --config flag: ``load_config()`` reads
    ``Path.home()/".atn"/"config.yaml"``. We redirect ``Path.home()`` for the
    child via USERPROFILE (ntpath.expanduser honours it), so this file IS the
    child's config.
    """
    import yaml
    atn_home = home / ".atn"
    atn_home.mkdir(parents=True, exist_ok=True)
    path = atn_home / "config.yaml"
    path.write_text(yaml.safe_dump(cfg, sort_keys=False), encoding="utf-8")
    return path


def daemon_env(home: Path) -> Dict[str, str]:
    """Environment for a daemon subprocess with a fully redirected home.

    ``Path.home()`` on Windows resolves USERPROFILE, then HOMEDRIVE+HOMEPATH,
    then HOME. All four are typically set, so redirecting USERPROFILE alone
    leaves HOMEDRIVE/HOMEPATH able to leak the real home to anything that reads
    them directly — clear them too. On POSIX, HOME is the one that matters.
    """
    env = dict(os.environ)
    env["USERPROFILE"] = str(home)
    env["HOME"] = str(home)
    env.pop("HOMEDRIVE", None)
    env.pop("HOMEPATH", None)
    # The repo root is on sys.path via cwd; make it explicit since we launch
    # the child from the temp home (NOT the repo) on purpose — see below.
    existing = env.get("PYTHONPATH", "")
    env["PYTHONPATH"] = (f"{REPO}{os.pathsep}{existing}" if existing
                         else str(REPO))
    env["PYTHONUNBUFFERED"] = "1"
    # Keep the child's ollama pointed where we probed.
    env["OLLAMA_HOST"] = OLLAMA_URL
    return env


def start_daemon(home: Path, label: str) -> subprocess.Popen:
    """Launch a REAL ``python -m atn`` daemon in an isolated home.

    Two subtleties that are easy to get wrong:

    * **cwd must NOT be the repo.** ``_default_agents_dir`` checks for a
      relative ``agents/`` directory in the CWD and returns it if present,
      BEFORE consulting data_dir. Launched from the repo root, an "isolated"
      daemon would happily share ``C:\\code\\autonet\\agents``. We launch from
      the temp home and put the repo on PYTHONPATH instead.
    * **stdin must stay OPEN.** ``_input_loop`` reads stdin and breaks on EOF,
      which shuts the daemon down. A closed/DEVNULL stdin makes the daemon exit
      seconds after boot. We hand it a pipe and never close it.
    """
    stdout_path = home / f"{label}.log"
    fh = open(stdout_path, "w", encoding="utf-8", errors="replace")
    proc = subprocess.Popen(
        [sys.executable, "-m", "atn"],
        cwd=str(home),                       # NOT the repo — see docstring
        env=daemon_env(home),
        stdin=subprocess.PIPE,               # stays open; EOF would shut down
        stdout=fh, stderr=subprocess.STDOUT,
        creationflags=(subprocess.CREATE_NEW_PROCESS_GROUP
                       if os.name == "nt" else 0),
    )
    proc._e2e_log = stdout_path              # type: ignore[attr-defined]
    proc._e2e_fh = fh                        # type: ignore[attr-defined]
    return proc


def daemon_tail(proc: Optional[subprocess.Popen], n: int = 40) -> str:
    """Last n lines of a daemon's log — the only diagnostic when boot fails."""
    if proc is None:
        return "(no process)"
    path = getattr(proc, "_e2e_log", None)
    if not path or not Path(path).exists():
        return "(no log)"
    try:
        lines = Path(path).read_text(encoding="utf-8",
                                     errors="replace").splitlines()
    except OSError as exc:
        return f"(unreadable: {exc})"
    return "\n".join(f"    | {ln}" for ln in lines[-n:])


class DaemonClient:
    """A WS client for one real daemon, speaking the production frames.

    Connects to the PRIVILEGED LOCAL listener (loopback), which is what a
    local app gets: pre-authed as owner, no handshake. Every call is a real
    frame over a real socket into a real process.
    """

    def __init__(self, url: str, label: str) -> None:
        self.url = url
        self.label = label
        self._ws: Any = None
        self._seq = 0

    async def connect(self, timeout: float = DAEMON_BOOT_TIMEOUT) -> None:
        """Dial with retries: the daemon's port LISTENS before the runtime has
        finished booting (heavy imports), so an early connect can be accepted
        and then hang. Retry the whole handshake, and prove liveness with a
        real ``snapshot`` round trip before declaring the daemon up.
        """
        import websockets

        deadline = time.time() + timeout
        last: Exception | None = None
        attempt = 0
        while time.time() < deadline:
            attempt += 1
            try:
                # A generous ping timeout: a service_request drives real
                # inference, and if the daemon ever stalls the loop (the bug
                # this script found in the payment gate) a tight keepalive
                # drops the connection mid-request and reports a transport
                # error for what is really a server-side stall. Keep the
                # keepalive on — a silent dead socket is worse — just patient.
                self._ws = await websockets.connect(
                    self.url, open_timeout=15,
                    ping_interval=20, ping_timeout=120,
                    max_size=16 * 1024 * 1024)
                # Liveness probe, not just a TCP accept.
                await self.call({"type": "snapshot"}, timeout=45.0)
                log(f"{self.label} up at {self.url} (attempt {attempt})")
                return
            except Exception as exc:  # noqa: BLE001
                last = exc
                if self._ws is not None:
                    try:
                        await self._ws.close()
                    except Exception:
                        pass
                    self._ws = None
                await asyncio.sleep(2.0)
        raise RuntimeError(
            f"{self.label} never answered at {self.url} after {attempt} "
            f"attempts: {last!r}")

    async def call(self, frame: Dict[str, Any], *,
                   timeout: float = WS_CALL_TIMEOUT) -> Dict[str, Any]:
        """One request/response. The daemon broadcasts events on the same
        socket, so read until the reply carrying OUR msg_id arrives."""
        if self._ws is None:
            raise RuntimeError(f"{self.label} not connected")
        self._seq += 1
        msg_id = f"{self.label}-{self._seq}"
        frame = dict(frame)
        frame["msg_id"] = msg_id
        await self._ws.send(json.dumps(frame))
        deadline = time.time() + timeout
        while time.time() < deadline:
            remaining = max(1.0, deadline - time.time())
            raw = await asyncio.wait_for(self._ws.recv(), timeout=remaining)
            try:
                msg = json.loads(raw)
            except (TypeError, json.JSONDecodeError):
                continue
            if isinstance(msg, dict) and msg.get("msg_id") == msg_id:
                return msg
        raise TimeoutError(
            f"{self.label}: no reply to {frame.get('type')} in {timeout}s")

    async def ok(self, frame: Dict[str, Any], *,
                 timeout: float = WS_CALL_TIMEOUT) -> Dict[str, Any]:
        """Call and require ok:true, returning the result payload."""
        reply = await self.call(frame, timeout=timeout)
        if not reply.get("ok"):
            raise RuntimeError(
                f"{self.label}: {frame.get('type')} failed — "
                f"{reply.get('error')}")
        return reply.get("result") or {}

    async def close(self) -> None:
        if self._ws is not None:
            try:
                await self._ws.close()
            except Exception:
                pass
            self._ws = None


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

async def amain() -> int:  # noqa: C901 — a linear E2E script, staged for reading
    from web3 import Web3

    board = Board()
    hh_proc: Optional[subprocess.Popen] = None
    ollama_proc: Optional[subprocess.Popen] = None
    prov_proc: Optional[subprocess.Popen] = None
    cons_proc: Optional[subprocess.Popen] = None
    prov_client: Optional[DaemonClient] = None
    cons_client: Optional[DaemonClient] = None
    tmp_prov = Path(tempfile.mkdtemp(prefix="e2e_xd_provider_"))
    tmp_cons = Path(tempfile.mkdtemp(prefix="e2e_xd_consumer_"))
    failed = False

    def teardown_all() -> None:
        kill_proc_tree(prov_proc, "provider daemon")
        kill_proc_tree(cons_proc, "consumer daemon")
        kill_proc_tree(hh_proc, "hardhat")
        kill_proc_tree(ollama_proc, "ollama (we started it)")

    try:
        # ------------------------------------------------------------------
        # Stage 1 — chain up
        # ------------------------------------------------------------------
        s1 = board.stage(1, "chain up (hardhat + Substrate + ServiceRegistry)")
        addresses: Dict[str, Optional[str]] = {}
        try:
            if SKIP_PROVIDER:
                # Split run: the chain lives on the PROVIDER box. We must not
                # start one (a second chain has neither the deployed contracts
                # nor the provider's registrations) — only dial it.
                if not (EXT_SUBSTRATE and EXT_REGISTRY):
                    raise RuntimeError(
                        "E2E_SKIP_PROVIDER=1 needs E2E_SUBSTRATE and "
                        "E2E_SERVICE_REGISTRY (printed by the hold side)")
                if not wait_rpc(60.0):
                    raise RuntimeError(
                        f"the provider box's chain is not reachable at "
                        f"{RPC_URL} (firewall? wrong host?)")
                addresses = {"substrate": EXT_SUBSTRATE,
                             "serviceRegistry": EXT_REGISTRY}
                s1.note("mode", "remote chain (provider box)")
            else:
                hh_proc = start_hardhat(REPO)
                if not wait_rpc(60.0):
                    raise RuntimeError(f"hardhat RPC never came up at {RPC_URL}")
                addresses = deploy_contracts(REPO)
            s1.note("rpc", RPC_URL)
            s1.note("hardhat_bind", HARDHAT_HOST)
            s1.note("substrate", addresses["substrate"])
            s1.note("serviceRegistry", addresses["serviceRegistry"])
            step(f"chain up; Substrate at {addresses['substrate']}")
            s1.status = "PASS"
        except _SkipStage:
            pass
        except Exception as e:
            s1.status = "FAIL"
            s1.note("error", repr(e))
            log(traceback.format_exc())
            print(_safe(board.render()))
            teardown_all()
            return 1

        w3 = Web3(Web3.HTTPProvider(RPC_URL))
        substrate_abi = load_abi("Substrate")
        substrate = w3.eth.contract(
            address=Web3.to_checksum_address(addresses["substrate"]),
            abi=substrate_abi)
        registry_c = w3.eth.contract(
            address=Web3.to_checksum_address(addresses["serviceRegistry"]),
            abi=load_abi("ServiceRegistry"))

        from eth_account import Account
        owner_prov = Account.from_key(HH_ACCT0_PK)   # seller's human wallet
        owner_cons = Account.from_key(HH_ACCT1_PK)   # employer's human wallet
        shape = resolve_binding_shape(substrate_abi)
        if shape["register"] is None or shape["hash_view"] is None:
            log(f"contract exposes no owner-binding surface: {shape}")

        # ------------------------------------------------------------------
        # Stage 2 — the REAL model
        # ------------------------------------------------------------------
        s2 = board.stage(2, "real model up (ollama + installed model)")
        model = MODEL
        try:
            if SKIP_PROVIDER:
                # The model is the PROVIDER's stack, on the other box. The
                # consumer deliberately has none — that is the whole test.
                if not model:
                    raise RuntimeError(
                        "E2E_SKIP_PROVIDER=1 needs E2E_MODEL (the id the "
                        "provider box is serving — printed by the hold side)")
                s2.note("served_by", "provider box")
                s2.note("model", model)
                s2.status = "SKIP"
                log(f"model {model} is served remotely by the provider box")
            else:
                installed = probe_ollama()
                if not installed:
                    ollama_proc = maybe_start_ollama()
                    installed = probe_ollama()
                if not installed:
                    raise RuntimeError(
                        f"no reachable ollama at {OLLAMA_URL} with an installed "
                        f"model. This script refuses to run against a canned "
                        f"model — the whole point is that a REAL model serves. "
                        f"Start ollama and `ollama pull` any small model, or set "
                        f"E2E_OLLAMA_URL / E2E_MODEL.")
                if model and model not in installed:
                    raise RuntimeError(
                        f"E2E_MODEL={model!r} is not installed "
                        f"(have: {installed})")
                if not model:
                    # Prefer an instruction-following chat model. A "thinker" /
                    # reasoning model will happily emit 500 tokens of
                    # deliberation before the one word we asked for, which the
                    # token cap then truncates — a flaky test for a reason that
                    # has nothing to do with the rail under test. Any installed
                    # model still works via E2E_MODEL.
                    preferred = [m for m in installed
                                 if not any(bad in m.lower()
                                            for bad in ("think", "reason",
                                                        "-r1"))]
                    model = (preferred or installed)[0]
                if not warm_model(model):
                    raise RuntimeError(
                        f"model {model} would not answer a warm-up")
                s2.note("backend", OLLAMA_URL)
                s2.note("model", model)
                s2.note("installed", ",".join(installed))
                step(f"real model ready: {model} at {OLLAMA_URL}")
                s2.status = "PASS"
        except _SkipStage:
            pass
        except Exception as e:
            s2.status = "FAIL"
            s2.note("error", repr(e))
            log(traceback.format_exc())
            print(_safe(board.render()))
            teardown_all()
            return 1

        # ------------------------------------------------------------------
        # Stage 3 — the PROVIDER daemon (real subprocess)
        # ------------------------------------------------------------------
        s3 = board.stage(3, "provider daemon (real `python -m atn` subprocess)")
        try:
            # The seller's daemon config. `sponsor_provider: ollama` is what
            # makes the inference-service dispatch resolve the LOCAL MODEL:
            # `_resolve_sponsor_provider` otherwise guesses by model-name
            # prefix and defaults to anthropic (an API key we deliberately do
            # not have here).
            prov_autonet: Dict[str, Any] = {
                    "enabled": False,          # no p2p/epoch machinery needed
                    "local_ws_port": PROVIDER_PORT,
                    "owner_wallet": owner_prov.address,
                    "private_key": owner_prov._private_key.hex(),
                    "rpc_url": RPC_URL,
                    "chain_id": CHAIN_ID,
                    "substrate_address": addresses["substrate"],
                    "service_registry_address": addresses["serviceRegistry"],
                    # The seller sells cognition off its own stack.
                    "sponsor_provider": "ollama",
                    "sponsor_model": model,
            }
            if PROVIDER_OFFBOX:
                # The privileged listener is loopback-pinned in atn/cli.py, so
                # an off-box buyer has to arrive on the REMOTE listener. Only
                # `service_request` is reachable there without the handshake,
                # and only because the payment is the credential — see the
                # module docstring.
                prov_autonet["remote_ws_host"] = PROVIDER_HOST
                prov_autonet["remote_ws_port"] = PROVIDER_REMOTE_PORT
            write_daemon_config(tmp_prov, cfg={
                "autonet": prov_autonet,
                "providers": {
                    "ollama": {"base_url": OLLAMA_URL, "default_model": model},
                },
                "voice": {"enabled": False},
                "auto_update": {"enabled": False},
            })
            if SKIP_PROVIDER:
                s3.note("skipped", "E2E_SKIP_PROVIDER=1")
                s3.note("assumed_at", PROVIDER_WS)
                s3.status = "SKIP"
                log(f"assuming an external provider daemon at {PROVIDER_WS}")
            else:
                prov_proc = start_daemon(tmp_prov, "provider")
                prov_client = DaemonClient(
                    f"ws://127.0.0.1:{PROVIDER_PORT}", "provider")
                await prov_client.connect()
                # Prove the isolation held: the daemon must be living in OUR
                # temp home, not the user's real ~/.atn (which has a LIVE
                # daemon on 7700 — sharing state would corrupt it).
                snap = await prov_client.ok({"type": "snapshot"})
                s3.note("home", str(tmp_prov))
                s3.note("port", PROVIDER_PORT)
                s3.note("pid", prov_proc.pid)
                s3.note("agents_at_boot", len(snap.get("agents") or []))
                step(f"provider daemon live on :{PROVIDER_PORT} "
                     f"(pid {prov_proc.pid}, home {tmp_prov.name})")
                s3.status = "PASS"
        except _SkipStage:
            pass
        except Exception as e:
            s3.status = "FAIL"
            s3.note("error", repr(e))
            log(traceback.format_exc())
            log(f"provider daemon log tail:\n{daemon_tail(prov_proc)}")
            print(_safe(board.render()))
            teardown_all()
            return 1

        # ------------------------------------------------------------------
        # Stage 4 — the CONSUMER daemon (second real subprocess)
        # ------------------------------------------------------------------
        s4 = board.stage(4, "consumer daemon (second real subprocess)")
        try:
            if PROVIDER_HOLD:
                s4.note("skipped", "E2E_PROVIDER_HOLD=1 (consumer is remote)")
                s4.status = "SKIP"
                raise _SkipStage
            write_daemon_config(tmp_cons, cfg={
                "autonet": {
                    "enabled": False,
                    "local_ws_port": CONSUMER_PORT,
                    "owner_wallet": owner_cons.address,
                    "private_key": owner_cons._private_key.hex(),
                    "rpc_url": RPC_URL,
                    "chain_id": CHAIN_ID,
                    "substrate_address": addresses["substrate"],
                    "service_registry_address": addresses["serviceRegistry"],
                    # DELIBERATELY no provider stack of its own: the child must
                    # think on PURCHASED cognition or not at all. If the binding
                    # silently fell back to a local model the test would pass
                    # while proving nothing.
                },
                "voice": {"enabled": False},
                "auto_update": {"enabled": False},
            })
            cons_proc = start_daemon(tmp_cons, "consumer")
            cons_client = DaemonClient(
                f"ws://127.0.0.1:{CONSUMER_PORT}", "consumer")
            await cons_client.connect()
            s4.note("home", str(tmp_cons))
            s4.note("port", CONSUMER_PORT)
            s4.note("pid", cons_proc.pid)
            s4.note("distinct_processes", prov_proc is None or
                    prov_proc.pid != cons_proc.pid)
            step(f"consumer daemon live on :{CONSUMER_PORT} "
                 f"(pid {cons_proc.pid}, home {tmp_cons.name})")
            s4.status = "PASS"
        except _SkipStage:
            pass
        except Exception as e:
            s4.status = "FAIL"
            s4.note("error", repr(e))
            log(traceback.format_exc())
            log(f"consumer daemon log tail:\n{daemon_tail(cons_proc)}")
            print(_safe(board.render()))
            teardown_all()
            return 1

        # ------------------------------------------------------------------
        # Stage 5 — agents, on chain, funded
        # ------------------------------------------------------------------
        s5 = board.stage(5, "agents on chain (provider, parent, funded child)")
        prov_agent = "provider-1"
        parent_agent = "parent-1"
        child_agent = "child-1"
        prov_addr = parent_addr = child_addr = ""
        prov_key = child_key = ""
        try:
            # NOTE on `system_prompt` vs `prompt`: `create_agent`'s ``prompt`` is
            # a WORK INSTRUCTION — it activates the agent and immediately
            # trigger_run()s it. Passing one here made all three agents start
            # thinking the moment they were created, which (a) queued the
            # provider daemon's own agent ahead of the buyer's paid work item on
            # the single local model, failing the purchase, and (b) burned the
            # model on nothing. Identity belongs in ``system_prompt``, which
            # registers the agent IDLE. The only turn in this script is the one
            # we drive deliberately in stage 7.
            if cons_client is not None:
                await cons_client.ok({
                    "type": "create_agent", "id": parent_agent,
                    "name": parent_agent, "mode": "cognitive",
                    "system_prompt": "You are the employer.",
                    "model": model,
                })
            # The provider's selling agent. Its 0x is the payment recipient the
            # gate checks, so it must be a real registered identity. It never
            # runs a turn of its own — it exists to be paid.
            if prov_client is None:
                # Split run: the selling agent lives on the provider box and is
                # already registered there. We only need its 0x to check the
                # payment event's recipient.
                if not EXT_PROVIDER_ADDR:
                    raise RuntimeError(
                        "E2E_SKIP_PROVIDER=1 needs E2E_PROVIDER_ADDR (the "
                        "selling agent's 0x — printed by the hold side)")
                prov_addr = Web3.to_checksum_address(EXT_PROVIDER_ADDR)
            if prov_client is not None:
                await prov_client.ok({
                    "type": "create_agent", "id": prov_agent,
                    "name": prov_agent, "mode": "cognitive",
                    "system_prompt": "You sell cognition.",
                    "model": model,
                })
                exported = await prov_client.ok({
                    "type": "export_agent_key", "agent_id": prov_agent})
                prov_key = exported["private_key"]
                prov_addr = Web3.to_checksum_address(exported["address"])

            # The CHILD: created BY the parent (caller_id=parent) so parent_id
            # is derived. The binding needs a service that does not exist yet,
            # so it is applied in stage 7 — which is also where the parent-only
            # enforcement gets exercised.
            child_atn = 0
            if cons_client is not None:
                await cons_client.ok({
                    "type": "create_agent", "caller_id": parent_agent,
                    "id": child_agent, "name": child_agent,
                    "mode": "cognitive",
                    "system_prompt": "Answer exactly what you are asked, "
                                     "nothing more. Never use tools.",
                    "model": model,
                })
                p_exp = await cons_client.ok({
                    "type": "export_agent_key", "agent_id": parent_agent})
                c_exp = await cons_client.ok({
                    "type": "export_agent_key", "agent_id": child_agent})
                parent_addr = Web3.to_checksum_address(p_exp["address"])
                child_addr = Web3.to_checksum_address(c_exp["address"])
                child_key = c_exp["private_key"]
                assert child_key and child_key != p_exp["private_key"], (
                    "the child must hold its OWN distinct wallet key")

            # Gas for every agent that signs.
            for owner, addr in ((owner_prov, prov_addr if prov_key else ""),
                                (owner_cons, parent_addr),
                                (owner_cons, child_addr)):
                if addr:
                    fund_gas(w3, owner, addr)

            # On-chain identities. The child's is what makes it a payer of
            # record; the provider's is the payment recipient. Each side
            # registers only the agents it actually holds keys for.
            regs = [(prov_key, prov_addr, owner_prov, b"peer-provider"),
                    (child_key, child_addr, owner_cons, b"peer-child")]
            for pk, addr, owner, peer in regs:
                if not (addr and pk):
                    continue
                lineage = bytes.fromhex(
                    Web3.keccak(text=addr).hex().replace("0x", "")[:64])
                register_agent_on_chain(
                    w3, substrate, shape, agent_pk=pk, agent_addr=addr,
                    owner_acct=owner, lineage_hash=lineage, peer_id=peer)

            # Fund the child's own wallet through the production mint rail.
            # The epoch id is per-box: submitAnchor hash-chains and refuses a
            # duplicate, so a split run's two sides must not claim the same one.
            if child_addr and child_key:
                child_atn = fund_agent_atn(
                    w3, substrate,
                    epoch_id=("e2e-xdaemon-consumer-1" if SKIP_PROVIDER
                              else "e2e-xdaemon-epoch-1"),
                    agent_addr=child_addr, agent_key=child_key,
                    amount=CHILD_FUNDING,
                    anchor_pk=owner_cons._private_key.hex() if SKIP_PROVIDER
                    else owner_prov._private_key.hex(),
                    anchor_addr=(owner_cons.address if SKIP_PROVIDER
                                 else owner_prov.address))
                assert child_atn >= SERVICE_ASK, (
                    f"child holds {child_atn}, needs >= {SERVICE_ASK}")

            s5.note("provider_agent", prov_addr)
            s5.note("parent_agent", parent_addr)
            s5.note("child_agent", child_addr)
            s5.note("child_atn", child_atn)
            step(f"agents on chain; child wallet funded with {child_atn} ATN")
            s5.status = "PASS"
        except _SkipStage:
            pass
        except Exception as e:
            s5.status = "FAIL"
            s5.note("error", repr(e))
            log(traceback.format_exc())
            print(_safe(board.render()))
            teardown_all()
            return 1

        # ------------------------------------------------------------------
        # Stage 6 — the provider lists inference for sale
        # ------------------------------------------------------------------
        s6 = board.stage(6, "provider lists an inference-backed service")
        spec_digest = ""
        try:
            if prov_client is None:
                # Split run: the provider box listed it. Verify the listing is
                # really there ON CHAIN (registry + endpoint) rather than
                # trusting the env — that is the whole discovery path.
                if not EXT_SPEC_DIGEST:
                    raise RuntimeError(
                        "E2E_SKIP_PROVIDER=1 needs E2E_SPEC_DIGEST (printed by "
                        "the hold side)")
                spec_digest = EXT_SPEC_DIGEST
                from atn.on_chain import OnChainService
                from atn.config import AutonetConfig
                from atn import service_client as _sc

                chain_cfg = AutonetConfig(
                    rpc_url=RPC_URL, chain_id=CHAIN_ID,
                    substrate_address=addresses["substrate"] or "",
                    service_registry_address=addresses["serviceRegistry"] or "")
                ask_info = await _sc.lookup_service_ask(
                    chain_cfg, prov_addr, spec_digest)
                if ask_info.get("error"):
                    raise RuntimeError(
                        f"the provider's service is not on chain: "
                        f"{ask_info['error']}")
                resolved = await OnChainService(
                    chain_cfg).get_agent_endpoint(prov_addr)
                if not resolved:
                    raise RuntimeError(
                        f"provider {prov_addr} published no ws endpoint on "
                        f"chain — nothing to dial")
                s6.note("mode", "listed by the provider box")
                s6.note("spec_digest", spec_digest[:16])
                s6.note("service_id", ask_info.get("service_id"))
                s6.note("ask_on_chain", ask_info.get("ask_amount"))
                s6.note("endpoint_resolved", resolved)
                step(f"resolved the provider's listing from chain: "
                     f"id={ask_info.get('service_id')}, ask="
                     f"{ask_info.get('ask_amount')}, endpoint {resolved}")
                s6.status = "PASS"
                raise _SkipStage
            reg = await prov_client.ok({
                "type": "register_service",
                "name": "real-cognition",
                "description": f"Chat completions off a real {model}.",
                "input_schema": {"type": "object",
                                 "properties": {"messages": {"type": "array"}}},
                "agent_id": prov_agent,
                # `ask.token` is still REQUIRED by validate_ask even though
                # settlement is ATN-only (ratified 2026-07-10) — the spec
                # validator predates that and the sibling script feeds it the
                # Substrate address too. Not this script's rail to change.
                "ask": {"token": addresses["substrate"],
                        "amount": str(SERVICE_ASK), "unit": "per_item"},
                "inference": {"model": model,
                              "max_tokens_cap": MAX_TOKENS_CAP},
            })
            spec_digest = reg["digest"]
            # The gate verifies the payment recipient against author_pubkey, so
            # the spec must be stamped with the selling agent's own 0x.
            listed = await prov_client.ok({"type": "list_services"})
            mine = next(s for s in listed["services"]
                        if s["digest"] == spec_digest)
            assert mine["inference"].get("model") == model, mine
            assert mine["inference"].get("max_tokens_cap") == MAX_TOKENS_CAP

            # On-chain listing, signed by the selling AGENT's key.
            send_tx(w3,
                    registry_c.functions.registerService(
                        bytes.fromhex(spec_digest), SERVICE_ASK),
                    prov_key, prov_addr)
            service_id = registry_c.functions.serviceCount().call()

            # Publish the reachable ws endpoint ON CHAIN. This is how the
            # consumer finds the counterparty — nothing is hardcoded on the
            # buying side, which is exactly what lets the consumer sit on
            # another machine (E2E_PROVIDER_WS carries the reachable address).
            from atn.on_chain import OnChainService
            from atn.config import AutonetConfig

            chain_cfg = AutonetConfig(
                rpc_url=RPC_URL, chain_id=CHAIN_ID,
                substrate_address=addresses["substrate"] or "",
                service_registry_address=addresses["serviceRegistry"] or "")
            oc = OnChainService(chain_cfg)
            ep = await oc.update_endpoint(prov_key, PROVIDER_WS)
            if not ep.get("success"):
                raise RuntimeError(f"updateEndpoint failed: {ep}")
            resolved = await oc.get_agent_endpoint(prov_addr)
            assert resolved == PROVIDER_WS, (resolved, PROVIDER_WS)

            s6.note("spec_digest", spec_digest[:16])
            s6.note("service_id", service_id)
            s6.note("ask", SERVICE_ASK)
            s6.note("served_model", model)
            s6.note("endpoint_on_chain", PROVIDER_WS)
            step(f"service listed (id={service_id}, ask={SERVICE_ASK}, "
                 f"endpoint {PROVIDER_WS})")
            s6.status = "PASS"
        except _SkipStage:
            pass
        except Exception as e:
            s6.status = "FAIL"
            s6.note("error", repr(e))
            log(traceback.format_exc())
            print(_safe(board.render()))
            teardown_all()
            return 1

        # ------------------------------------------------------------------
        # HOLD — provider side only: hand the consumer box its exports and wait
        # ------------------------------------------------------------------
        if PROVIDER_HOLD:
            sentinel = Path(HOLD_SENTINEL) if HOLD_SENTINEL else (
                tmp_prov / "e2e_provider_release")
            # The consumer must dial a REACHABLE rpc. Ours is usually the
            # loopback default while hardhat binds 0.0.0.0, so advertise the
            # host the buyer already reaches us on (from E2E_PROVIDER_WS)
            # rather than handing it a 127.0.0.1 it would resolve to itself.
            adv_rpc = RPC_URL
            try:
                from urllib.parse import urlsplit
                rpc_parts = urlsplit(RPC_URL)
                ws_host = urlsplit(PROVIDER_WS).hostname or ""
                if (rpc_parts.hostname in ("127.0.0.1", "localhost", "::1")
                        and ws_host
                        and ws_host not in ("127.0.0.1", "localhost", "::1")):
                    adv_rpc = (f"{rpc_parts.scheme}://{ws_host}"
                               f":{rpc_parts.port or 8545}")
            except Exception:  # noqa: BLE001 — advertising is best-effort
                pass
            exports = [
                ("E2E_SKIP_PROVIDER", "1"),
                ("E2E_RPC_URL", adv_rpc),
                ("E2E_PROVIDER_WS", PROVIDER_WS),
                ("E2E_SUBSTRATE", str(addresses["substrate"])),
                ("E2E_SERVICE_REGISTRY", str(addresses["serviceRegistry"])),
                ("E2E_SPEC_DIGEST", spec_digest),
                ("E2E_PROVIDER_ADDR", prov_addr),
                ("E2E_MODEL", model),
            ]
            print("")
            print("=" * 74)
            print("  PROVIDER SIDE IS UP AND HOLDING — run the consumer half")
            print("  with this environment on the other box:")
            print("=" * 74)
            for k, v in exports:
                print(f"export {k}={v}")
            print("=" * 74)
            print(f"  release: Ctrl+C, or `touch {sentinel}`")
            print(f"  provider home: {tmp_prov}")
            print(f"  provider log:  {getattr(prov_proc, '_e2e_log', '?')}")
            print("=" * 74, flush=True)
            # Machine-readable twin, so a driving script does not have to
            # scrape stdout.
            try:
                (tmp_prov / "e2e_exports.json").write_text(
                    json.dumps(dict(exports), indent=2), encoding="utf-8")
                log(f"exports also written to {tmp_prov / 'e2e_exports.json'}")
            except OSError:
                pass
            board.stage(7, "REAL agent turn (CONSUMER BOX)").status = "SKIP"
            board.stage(8, "settlement (CONSUMER BOX)").status = "SKIP"
            try:
                while True:
                    if sentinel.exists():
                        log("sentinel appeared — releasing the provider side")
                        break
                    if prov_proc is not None and prov_proc.poll() is not None:
                        log("provider daemon EXITED while holding; log tail:")
                        log(daemon_tail(prov_proc))
                        break
                    await asyncio.sleep(2.0)
            except (KeyboardInterrupt, asyncio.CancelledError):
                log("interrupted — releasing the provider side")
            print(_safe(board.render()))
            teardown_all()
            prov_proc = cons_proc = hh_proc = ollama_proc = None
            return 0

        # ------------------------------------------------------------------
        # Stage 7 — bind the child, then a REAL agent turn on bought cognition
        # ------------------------------------------------------------------
        s7 = board.stage(7, "REAL agent turn on purchased cognition")
        answer = ""
        prov_bal_before = substrate.functions.balanceOf(prov_addr).call()
        child_bal_before = substrate.functions.balanceOf(child_addr).call()
        owner_bal_before = substrate.functions.balanceOf(
            owner_cons.address).call()
        try:
            binding = {"provider_address": prov_addr,
                       "spec_digest": spec_digest}

            # The child may NOT bind itself (employer-chooses-the-tool).
            self_bind = await cons_client.call({
                "type": "update_agent", "caller_id": child_agent,
                "agent_id": child_agent, "service_provider": dict(binding)})
            assert not self_bind.get("ok"), (
                f"a child was allowed to set its OWN binding: {self_bind}")
            s7.note("child_self_bind_refused", True)

            # The PARENT may.
            bound = await cons_client.ok({
                "type": "update_agent", "caller_id": parent_agent,
                "agent_id": child_agent, "service_provider": dict(binding)})
            assert "service_provider" in (bound.get("changed") or []), bound
            step("parent bound the child to the purchased service")

            # ARM the child. A freshly created agent is REGISTERED, and
            # `send_agent_message` only TRIGGERS a run for an ACTIVE agent —
            # otherwise it just queues to the inbox and returns no
            # execution_id, and the turn silently never happens. Activating is
            # the production step (the `activate <id>` console command / the
            # UI's arm toggle), deliberately separate from creation so an agent
            # does not start thinking the moment it exists.
            await cons_client.ok({
                "type": "activate_agent", "agent_id": child_agent})

            # THE TURN. `send_agent_message` is the production surface a human's
            # app uses; the child resolves its bound ServiceProvider, pays from
            # its OWN wallet, dials the provider daemon over the real wss wire,
            # and a REAL model answers.
            sent = await cons_client.ok({
                "type": "send_agent_message", "agent_id": child_agent,
                "content": PROBE_PROMPT})
            execution_id = sent.get("execution_id") or ""
            s7.note("send_status", sent.get("status"))
            s7.note("execution_id", str(execution_id)[:16])
            if not execution_id:
                raise RuntimeError(
                    f"send_agent_message queued but did not TRIGGER a run "
                    f"(status={sent.get('status')!r}) — the child is not armed, "
                    f"so no turn would ever happen: {sent}")
            log(f"agent turn triggered ({execution_id}); waiting up to "
                f"{INFERENCE_TIMEOUT:.0f}s for real inference…")

            # Poll the execution record. Real inference over a real wire — be
            # generous, and surface the error rather than time out blind.
            deadline = time.time() + INFERENCE_TIMEOUT
            rec: Dict[str, Any] = {}
            while time.time() < deadline:
                rec = await cons_client.ok({
                    "type": "get_execution", "execution_id": execution_id},
                    timeout=60.0)
                if rec.get("status") in ("completed", "failed", "error"):
                    break
                await asyncio.sleep(3.0)
            s7.note("execution_status", rec.get("status"))
            if rec.get("error"):
                raise RuntimeError(f"the agent turn failed: {rec['error']}")

            # The answer. ``record.output`` is a dict whose ``result`` key holds
            # the model's own text (alongside tokens_used / usage / run_summary);
            # take that rather than the dict's repr, so the assertion is against
            # what the MODEL said and not against framework metadata that might
            # happen to contain the probe word.
            out = rec.get("output")
            if isinstance(out, dict):
                answer = str(out.get("result") or "")
                usage = out.get("usage") or {}
                s7.note("served_usage_out_tokens",
                        usage.get("output_tokens"))
            else:
                answer = str(out or "")
            if not answer:
                for sr in reversed(rec.get("steps") or []):
                    if sr.get("output"):
                        so = sr["output"]
                        answer = str(so.get("result") if isinstance(so, dict)
                                     else so)
                        if answer:
                            break
            log(f"model said: {answer[:400]!r}")

            # (a) REAL model output, not canned: non-empty AND it answers the
            #     distinguishable prompt. A fixed responder cannot echo a word
            #     chosen at test time.
            assert answer.strip(), (
                "the completion was EMPTY — no model output came back")
            assert MAGIC_WORD.lower() in answer.lower(), (
                f"the reply does not answer the distinguishable prompt "
                f"(wanted {MAGIC_WORD!r} in the answer): {answer[:300]!r}")
            s7.note("answer", answer.strip()[:80])
            s7.note("answers_distinguishable_prompt", True)
            step(f"REAL model answered the probe: {answer.strip()[:60]!r}")
            s7.status = "PASS"
        except _SkipStage:
            pass
        except Exception as e:
            s7.status = "FAIL"
            s7.note("error", repr(e))
            log(traceback.format_exc())
            log(f"consumer log tail:\n{daemon_tail(cons_proc)}")
            log(f"provider log tail:\n{daemon_tail(prov_proc)}")
            failed = True

        # ------------------------------------------------------------------
        # Stage 8 — settlement: money, provider log, replay refused
        # ------------------------------------------------------------------
        s8 = board.stage(8, "settlement (payment event, request log, replay)")
        try:
            if s7.status != "PASS":
                raise RuntimeError("stage 7 did not complete a paid turn")

            # (b) ServicePayment event: child payer, provider recipient, amount.
            # Scope to THIS child's payments: a split run shares one chain with
            # the provider box, which may have settled other traffic, and the
            # balance arithmetic below counts calls.
            def _payer_of(a: Dict[str, Any]) -> str:
                return str(a.get("payer") or a.get("client")
                           or a.get("from") or "")

            pay_logs = [
                lg for lg in
                substrate.events.ServicePayment().get_logs(from_block=0)
                if _payer_of(lg["args"]).lower() == child_addr.lower()]
            assert pay_logs, (
                "no ServicePayment event from the child on chain — nothing paid")
            ev = pay_logs[-1]["args"]
            assert ev["recipient"].lower() == prov_addr.lower(), ev
            payer = ev.get("payer") or ev.get("client") or ev.get("from")
            if payer is not None:
                assert str(payer).lower() == child_addr.lower(), (
                    payer, child_addr)
            assert int(ev["amount"]) == SERVICE_ASK, ev
            s8.note("payments", len(pay_logs))
            s8.note("event_payer", str(payer))
            s8.note("event_recipient", ev["recipient"])
            s8.note("event_amount", int(ev["amount"]))
            step("ServicePayment event: child payer, provider recipient, "
                 f"amount {SERVICE_ASK}")

            # The money moved from the RIGHT wallet, net of the 2.5% fee.
            fee = (SERVICE_ASK * 250) // 10000
            net = SERVICE_ASK - fee
            n_calls = len(pay_logs)
            prov_after = substrate.functions.balanceOf(prov_addr).call()
            child_after = substrate.functions.balanceOf(child_addr).call()
            owner_after = substrate.functions.balanceOf(
                owner_cons.address).call()
            assert child_bal_before - child_after == SERVICE_ASK * n_calls, (
                f"child paid {child_bal_before - child_after}, expected "
                f"{SERVICE_ASK * n_calls} over {n_calls} call(s)")
            assert prov_after - prov_bal_before == net * n_calls, (
                f"provider received {prov_after - prov_bal_before}, expected "
                f"{net * n_calls}")
            assert owner_after == owner_bal_before, (
                "the daemon OWNER's wallet moved — the child pays for itself")
            s8.note("child_debited", child_bal_before - child_after)
            s8.note("provider_credited_net", prov_after - prov_bal_before)
            s8.note("fee_burned_per_call", fee)
            s8.note("owner_wallet_untouched", True)
            step(f"child debited {SERVICE_ASK * n_calls}, provider credited "
                 f"{net * n_calls} net of fee; owner wallet untouched")

            # The request id the child actually paid on, in the two forms the
            # rest of this stage compares against.
            rid_raw = pay_logs[-1]["args"].get("requestId")
            rid_hex = (bytes(rid_raw).hex()
                       if isinstance(rid_raw, (bytes, bytearray))
                       else str(rid_raw or ""))
            rid = rid_hex.lower().removeprefix("0x")
            paid_tx = pay_logs[-1]["transactionHash"].hex()

            # (c) The PROVIDER daemon's own request log recorded the served
            #     item. Read off the provider's isolated home — a real process
            #     wrote this, which is the provider-side proof of service.
            #     In a split run those files are on the OTHER box; the provider
            #     side asserts them there, and the wire-level replay refusal
            #     below is the stronger cross-machine proof of the same gate.
            replay_rid = "0x" + rid
            if prov_client is not None:
                req_log = tmp_prov / ".atn" / "services" / "requests.jsonl"
                served_path = (tmp_prov / ".atn" / "services"
                               / "served_requests.json")
                assert req_log.exists(), (
                    f"provider recorded NO request log at {req_log}")
                rows = [json.loads(ln) for ln in
                        req_log.read_text(encoding="utf-8").splitlines()
                        if ln.strip()]
                mine_rows = [r for r in rows
                             if r.get("spec_digest") == spec_digest]
                assert mine_rows, (
                    f"no request-log row for {spec_digest[:16]}: {rows}")
                ok_rows = [r for r in mine_rows if r.get("ok")]
                assert ok_rows, (
                    f"the provider logged only FAILED requests: {mine_rows}")
                assert (ok_rows[-1].get("client", "").lower()
                        == child_addr.lower()), (ok_rows[-1], child_addr)
                s8.note("provider_log_rows", len(mine_rows))
                s8.note("provider_log_client", ok_rows[-1].get("client"))
                step(f"provider request log recorded {len(ok_rows)} served "
                     f"item(s) for the child")

                # The gate really VERIFIED rather than degrading open: a
                # degraded gate never consumes a request id, so the served set
                # would be empty.
                assert served_path.exists(), (
                    "the gate persisted NO served request ids — it DEGRADED "
                    "OPEN instead of verifying the payment on chain")
                served = json.loads(served_path.read_text(encoding="utf-8"))
                seen_norm = {str(r).lower().removeprefix("0x") for r in served}
                assert rid in seen_norm, (
                    f"paid request id {rid[:18]} was never marked served "
                    f"(gate saw {[s[:18] for s in seen_norm]}) — the payment "
                    f"verified was not the one made")
                s8.note("gate_verified_not_degraded", True)
                step("provider gate verified the payment on chain "
                     "(not degraded)")
                # Re-send the id in the EXACT form the gate stored it (the
                # served set is string-keyed).
                replay_rid = next(r for r in served
                                  if str(r).lower().removeprefix("0x") == rid)
            else:
                s8.note("provider_log", "on the provider box (not readable "
                                        "from here)")

            # (d) A REPLAYED request_id is refused. Cross-machine this goes over
            #     the SAME wire the child used, through service_client — which
            #     is also the proof that the remote listener accepts a paying
            #     stranger's service_request and nothing else.
            if prov_client is not None:
                replay = await prov_client.call({
                    "type": "service_request",
                    "spec_digest": spec_digest,
                    "request_id": replay_rid,
                    "args": {"messages": [{"role": "user",
                                           "content": "replay"}]},
                    "client": child_addr,
                    "tx_hash": paid_tx,
                })
            else:
                from atn import service_client as _sc
                from atn.config import AutonetConfig as _AC

                wire = await _sc.request_service(
                    _AC(rpc_url=RPC_URL, chain_id=CHAIN_ID,
                        substrate_address=addresses["substrate"] or "",
                        service_registry_address=(
                            addresses["serviceRegistry"] or "")),
                    prov_addr, spec_digest,
                    {"messages": [{"role": "user", "content": "replay"}]},
                    tx_hash=paid_tx, request_id=replay_rid,
                    client_address=child_addr, timeout=60.0)
                if wire.get("error") and wire.get("ok") is None:
                    raise RuntimeError(
                        f"the replay probe never reached the provider: "
                        f"{wire['error']}")
                replay = {"ok": wire.get("ok"), "error": wire.get("error")}
                s8.note("replay_over_wire", wire.get("endpoint"))
            assert not replay.get("ok"), (
                f"the gate ACCEPTED a replayed request_id: {replay}")
            err = str(replay.get("error", "")).lower()
            assert "replay" in err or "already served" in err, replay
            s8.note("replay_refused", True)
            s8.note("replay_error", str(replay.get("error"))[:70])
            step("gate refuses a replayed request_id")
            s8.status = "PASS"
        except _SkipStage:
            pass
        except Exception as e:
            s8.status = "FAIL"
            s8.note("error", repr(e))
            log(traceback.format_exc())
            failed = True

        # ------------------------------------------------------------------
        # Stage 9 — teardown
        # ------------------------------------------------------------------
        s9 = board.stage(9, "teardown (both daemons, chain)")
        try:
            for c in (prov_client, cons_client):
                if c is not None:
                    await c.close()
            teardown_all()
            prov_proc = cons_proc = hh_proc = ollama_proc = None
            s9.status = "PASS"
            step("both daemons and the chain torn down")
        except _SkipStage:
            pass
        except Exception as e:
            s9.status = "FAIL"
            s9.note("error", repr(e))
            log(traceback.format_exc())
            failed = True

        print(_safe(board.render()))
        if s7.status == "PASS" and answer:
            print(f"\n  MODEL OUTPUT ({model}):\n    {answer.strip()[:600]}\n")
        any_fail = any(s.status == "FAIL" for s in board.stages.values())
        return 1 if (failed or any_fail) else 0
    finally:
        # Belt and braces: never leave a daemon, a chain, or an ollama we
        # started running after this script exits, on ANY path.
        teardown_all()


def main() -> int:
    try:
        return asyncio.run(amain())
    except KeyboardInterrupt:
        return 130


if __name__ == "__main__":
    sys.exit(main())
